// Generated by update-stats.ps1 - do not edit by hand.
window.RIG_STATS = {
    "capturedAt":  "2026-10-04T06:35:16.6262073Z",
    "os":  "Microsoft Windows 11 Pro",
    "cpu":  {
                "name":  "AMD Ryzen 7 7800X3D 8-Core Processor",
                "cores":  8,
                "threads":  16,
                "baseClockMHz":  4201,
                "l2KB":  8192,
                "l3KB":  98304,
                "load":  1.2,
                "effectiveClockMHz":  4083,
                "coreLoads":  [
                                  0.2,
                                  1.8,
                                  0.2,
                                  4.9,
                                  0.2,
                                  0.2,
                                  0.2,
                                  0.2,
                                  0.2,
                                  1.8,
                                  0.2,
                                  0.2,
                                  0.2,
                                  1.8,
                                  3.4,
                                  0.2
                              ],
                "integratedGraphics":  "AMD Radeon(TM) Graphics"
            },
    "gpu":  {
                "name":  "NVIDIA GeForce RTX 4070 SUPER",
                "vramTotalMB":  12282,
                "vramUsedMB":  1455,
                "utilization":  3,
                "tempC":  47,
                "powerW":  8.59,
                "powerLimitW":  220,
                "clockMHz":  210,
                "maxClockMHz":  3105,
                "fanPercent":  0,
                "driver":  "617.14"
            },
    "display":  {
                    "width":  1920,
                    "height":  1080,
                    "hz":  120
                },
    "memory":  {
                   "totalGB":  31.1,
                   "usedGB":  9.8,
                   "modules":  [
                                   {
                                       "partNumber":  "F5-6000J3636F16G",
                                       "capacityGB":  16,
                                       "speedMTs":  4800,
                                       "type":  "DDR5"
                                   },
                                   {
                                       "partNumber":  "F5-6000J3636F16G",
                                       "capacityGB":  16,
                                       "speedMTs":  4800,
                                       "type":  "DDR5"
                                   }
                               ]
               },
    "motherboard":  {
                        "manufacturer":  "Gigabyte Technology Co., Ltd.",
                        "product":  "B650 AORUS ELITE AX",
                        "bios":  "FB2"
                    },
    "storage":  {
                    "name":  "KLEVV CRAS C910G M.2 NVMe SSD 1TB",
                    "bus":  "NVMe",
                    "mediaType":  "SSD",
                    "sizeGB":  1000,
                    "cTotalGB":  930.4,
                    "cUsedGB":  68.5,
                    "busyPercent":  2,
                    "readMBs":  0,
                    "writeMBs":  1.43
                }
};
